### PR TITLE
Adding disabled? method

### PR DESCRIPTION
**Pull request by serhii-bodnaruk**
## About the changes
Adding `disabled?` method to more comfort using Unleash.

### CODE REVIEW

**Comment by serhii-bodnaruk** [comment]
@sighphyre could you take a look?

**Comment by rarruda** [comment]
@sighphyre @gardleopard 

Opinions?

The things I can think of:

- not a method in the other SDKs (?!), so it would make the rundt SDK a bit off compared with the API in the other SDKs. (Looked at node, Java, and python SDKs)
- Maybe the recommended solution instead of `if client.disabled?("foo")` would be to use the `unless` keyword instead `unless client.enabled?("foo")`  (?!)
- Missing clone method `is_disabled?`, for the sake of consistency. 
- Missing opposite test, for completeness sake. (That the disabled is the opposite in both true and false scenarios).
- Missing docs in README (method description).

Wdyt?

**Comment by serhii-bodnaruk** [comment]
It's not looking good and well readable "unless" staff, we prefer not to use it in simple cases.
From the beginning I added the method `is_disabled?` but your CI and rubocop setup doesn't like it, so renamed the method and remove the alias.

I can add more tests and README, my bad. But in case you guys like the idea in general. If not we will patch it on our end, no problem. 🙏

**Comment by rarruda** [comment]
Those were my 2c/thoughts.

Let's wait for what @sighphyre and @gardleopard think/decide. 

But maybe @ivarconr would want to weigh in too?

**Review by gardleopard — CHANGES_REQUESTED** [review]
Hi, this looks good! Thank you for your contribution. We would like to see some updates in the README.md and then its good:)

**Review by gardleopard — APPROVED** [review]
Looks good, thanks for your contribution!

**Pull request merged**
