### PR TITLE
#31 - bugfix: respect retry_limit configuration parameter

### PR DESCRIPTION
**Pull request by rarruda**
configuration setting was never sent to ScheduledExecutor

### CODE REVIEW

**Comment by lexicalunit** [comment]
Curious, is there a way to say "make infinite retries" by setting this to 0?

**Comment by rarruda** [comment]
Not as is, but that’s very good feedback.

**Comment by rarruda** [comment]
After looking a bit more into this, i think it would be more elegant to just specify `Float::INFINITY` for explicitly never giving up.

However I see that it can be useful to document this use case, and will add info in the README.

**Comment by orlandojsjr** [comment]
Hey guys, @rarruda are you planning to launch a new release with this PR? ty

**Comment by rarruda** [comment]
@orlandojsjr A new release should be coming out soon!

**Pull request merged**
